<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%country}}`.
 */
class m201109_172533_create_country_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
      $tableOptions = null;
      if ($this->db->driverName === 'mysql') {
          // http://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci
          $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
      }


        $this->createTable('{{%country}}', [
            'country_id' => $this->primaryKey(),
            'country_name' => $this->string()->notNull(),
            'country_code' => $this->string()->notNull(),
            'country_status' => $this->smallInteger()->notNull()->defaultValue(1),
        ], $tableOptions);

        $sql = " INSERT INTO `country` (`country_id`, `country_name`, `country_code`, `country_status`) VALUES
                    (1, 'Afghanistan', 'AF', 10),
                    (2, 'Albania', 'AL', 10),
                    (3, 'Algeria', 'DZ', 10),
                    (4, 'American Samoa', 'AS', 10),
                    (5, 'Andorra', 'AD', 10),
                    (6, 'Angola', 'AO', 10),
                    (7, 'Anguilla', 'AI', 10),
                    (8, 'Antarctica', 'AQ', 10),
                    (9, 'Antigua and Barbuda', 'AG', 10),
                    (10, 'Argentina', 'AR', 10),
                    (11, 'Armenia', 'AM', 10),
                    (12, 'Aruba', 'AW', 10),
                    (13, 'Australia', 'AU', 10),
                    (14, 'Austria', 'AT', 10),
                    (15, 'Azerbaijan', 'AZ', 10),
                    (16, 'Bahamas', 'BS', 10),
                    (17, 'Bahrain', 'BH', 10),
                    (18, 'Bangladesh', 'BD', 10),
                    (19, 'Barbados', 'BB', 10),
                    (20, 'Belarus', 'BY', 10),
                    (21, 'Belgium', 'BE', 10),
                    (22, 'Belize', 'BZ', 10),
                    (23, 'Benin', 'BJ', 10),
                    (24, 'Bermuda', 'BM', 10),
                    (25, 'Bhutan', 'BT', 10),
                    (26, 'Bolivia', 'BO', 10),
                    (27, 'Bosnia and Herzegovina', 'BA', 10),
                    (28, 'Botswana', 'BW', 10),
                    (29, 'Bouvet Island', 'BV', 10),
                    (30, 'Brazil', 'BR', 10),
                    (31, 'British Indian Ocean Territory', 'IO', 10),
                    (32, 'Brunei Darussalam', 'BN', 10),
                    (33, 'Bulgaria', 'BG', 10),
                    (34, 'Burkina Faso', 'BF', 10),
                    (35, 'Burundi', 'BI', 10),
                    (36, 'Cambodia', 'KH', 10),
                    (37, 'Cameroon', 'CM', 10),
                    (38, 'Canada', 'CA', 10),
                    (39, 'Cape Verde', 'CV', 10),
                    (40, 'Cayman Islands', 'KY', 10),
                    (41, 'Central African Republic', 'CF', 10),
                    (42, 'Chad', 'TD', 10),
                    (43, 'Chile', 'CL', 10),
                    (44, 'China', 'CN', 10),
                    (45, 'Christmas Island', 'CX', 10),
                    (46, 'Cocos (Keeling) Islands', 'CC', 10),
                    (47, 'Colombia', 'CO', 10),
                    (48, 'Comoros', 'KM', 10),
                    (49, 'Congo', 'CG', 10),
                    (50, 'Cook Islands', 'CK', 10),
                    (51, 'Costa Rica', 'CR', 10),
                    (52, 'Cote D\'Ivoire', 'CI', 10),
                    (53, 'Croatia', 'HR', 10),
                    (54, 'Cuba', 'CU', 10),
                    (55, 'Cyprus', 'CY', 10),
                    (56, 'Czech Republic', 'CZ', 10),
                    (57, 'Denmark', 'DK', 10),
                    (58, 'Djibouti', 'DJ', 10),
                    (59, 'Dominica', 'DM', 10),
                    (60, 'Dominican Republic', 'DO', 10),
                    (61, 'East Timor', 'TL', 10),
                    (62, 'Ecuador', 'EC', 10),
                    (63, 'Egypt', 'EG', 10),
                    (64, 'El Salvador', 'SV', 10),
                    (65, 'Equatorial Guinea', 'GQ', 10),
                    (66, 'Eritrea', 'ER', 10),
                    (67, 'Estonia', 'EE', 10),
                    (68, 'Ethiopia', 'ET', 10),
                    (69, 'Falkland Islands (Malvinas)', 'FK', 10),
                    (70, 'Faroe Islands', 'FO', 10),
                    (71, 'Fiji', 'FJ', 10),
                    (72, 'Finland', 'FI', 10),
                    (74, 'France, Metropolitan', 'FR', 10),
                    (75, 'French Guiana', 'GF', 10),
                    (76, 'French Polynesia', 'PF', 10),
                    (77, 'French Southern Territories', 'TF', 10),
                    (78, 'Gabon', 'GA', 10),
                    (79, 'Gambia', 'GM', 10),
                    (80, 'Georgia', 'GE', 10),
                    (81, 'Germany', 'DE', 10),
                    (82, 'Ghana', 'GH', 10),
                    (83, 'Gibraltar', 'GI', 10),
                    (84, 'Greece', 'GR', 10),
                    (85, 'Greenland', 'GL', 10),
                    (86, 'Grenada', 'GD', 10),
                    (87, 'Guadeloupe', 'GP', 10),
                    (88, 'Guam', 'GU', 10),
                    (89, 'Guatemala', 'GT', 10),
                    (90, 'Guinea', 'GN', 10),
                    (91, 'Guinea-Bissau', 'GW', 10),
                    (92, 'Guyana', 'GY', 10),
                    (93, 'Haiti', 'HT', 10),
                    (94, 'Heard and Mc Donald Islands', 'HM', 10),
                    (95, 'Honduras', 'HN', 10),
                    (96, 'Hong Kong', 'HK', 10),
                    (97, 'Hungary', 'HU', 10),
                    (98, 'Iceland', 'IS', 10),
                    (99, 'India', 'IN', 10),
                    (100, 'Indonesia', 'ID', 10),
                    (101, 'Iran (Islamic Republic of)', 'IR', 10),
                    (102, 'Iraq', 'IQ', 10),
                    (103, 'Ireland', 'IE', 10),
                    (105, 'Italy', 'IT', 10),
                    (106, 'Jamaica', 'JM', 10),
                    (107, 'Japan', 'JP', 10),
                    (108, 'Jordan', 'JO', 10),
                    (109, 'Kazakhstan', 'KZ', 10),
                    (110, 'Kenya', 'KE', 10),
                    (111, 'Kiribati', 'KI', 10),
                    (112, 'North Korea', 'KP', 10),
                    (113, 'South Korea', 'KR', 10),
                    (114, 'Kuwait', 'KW', 10),
                    (115, 'Kyrgyzstan', 'KG', 10),
                    (116, 'Lao People\'s Democratic Republic', 'LA', 10),
                    (117, 'Latvia', 'LV', 10),
                    (118, 'Lebanon', 'LB', 10),
                    (119, 'Lesotho', 'LS', 10),
                    (120, 'Liberia', 'LR', 10),
                    (121, 'Libyan Arab Jamahiriya', 'LY', 10),
                    (122, 'Liechtenstein', 'LI', 10),
                    (123, 'Lithuania', 'LT', 10),
                    (124, 'Luxembourg', 'LU', 10),
                    (125, 'Macau', 'MO', 10),
                    (126, 'FYROM', 'MK', 10),
                    (127, 'Madagascar', 'MG', 10),
                    (128, 'Malawi', 'MW', 10),
                    (129, 'Malaysia', 'MY', 10),
                    (130, 'Maldives', 'MV', 10),
                    (131, 'Mali', 'ML', 10),
                    (132, 'Malta', 'MT', 10),
                    (133, 'Marshall Islands', 'MH', 10),
                    (134, 'Martinique', 'MQ', 10),
                    (135, 'Mauritania', 'MR', 10),
                    (136, 'Mauritius', 'MU', 10),
                    (137, 'Mayotte', 'YT', 10),
                    (138, 'Mexico', 'MX', 10),
                    (139, 'Micronesia, Federated States of', 'FM', 10),
                    (140, 'Moldova, Republic of', 'MD', 10),
                    (141, 'Monaco', 'MC', 10),
                    (142, 'Mongolia', 'MN', 10),
                    (143, 'Montserrat', 'MS', 10),
                    (144, 'Morocco', 'MA', 10),
                    (145, 'Mozambique', 'MZ', 10),
                    (146, 'Myanmar', 'MM', 10),
                    (147, 'Namibia', 'NA', 10),
                    (148, 'Nauru', 'NR', 10),
                    (149, 'Nepal', 'NP', 10),
                    (150, 'Netherlands', 'NL', 10),
                    (151, 'Netherlands Antilles', 'AN', 10),
                    (152, 'New Caledonia', 'NC', 10),
                    (153, 'New Zealand', 'NZ', 10),
                    (154, 'Nicaragua', 'NI', 10),
                    (155, 'Niger', 'NE', 10),
                    (156, 'Nigeria', 'NG', 10),
                    (157, 'Niue', 'NU', 10),
                    (158, 'Norfolk Island', 'NF', 10),
                    (159, 'Northern Mariana Islands', 'MP', 10),
                    (160, 'Norway', 'NO', 10),
                    (161, 'Oman', 'OM', 10),
                    (162, 'Pakistan', 'PK', 10),
                    (163, 'Palau', 'PW', 10),
                    (164, 'Panama', 'PA', 10),
                    (165, 'Papua New Guinea', 'PG', 10),
                    (166, 'Paraguay', 'PY', 10),
                    (167, 'Peru', 'PE', 10),
                    (168, 'Philippines', 'PH', 10),
                    (169, 'Pitcairn', 'PN', 10),
                    (170, 'Poland', 'PL', 10),
                    (171, 'Portugal', 'PT', 10),
                    (172, 'Puerto Rico', 'PR', 10),
                    (173, 'Qatar', 'QA', 10),
                    (174, 'Reunion', 'RE', 10),
                    (175, 'Romania', 'RO', 10),
                    (176, 'Russian Federation', 'RU', 10),
                    (177, 'Rwanda', 'RW', 10),
                    (178, 'Saint Kitts and Nevis', 'KN', 10),
                    (179, 'Saint Lucia', 'LC', 10),
                    (180, 'Saint Vincent and the Grenadines', 'VC', 10),
                    (181, 'Samoa', 'WS', 10),
                    (182, 'San Marino', 'SM', 10),
                    (183, 'Sao Tome and Principe', 'ST', 10),
                    (184, 'Saudi Arabia', 'SA', 10),
                    (185, 'Senegal', 'SN', 10),
                    (186, 'Seychelles', 'SC', 10),
                    (187, 'Sierra Leone', 'SL', 10),
                    (188, 'Singapore', 'SG', 10),
                    (189, 'Slovak Republic', 'SK', 10),
                    (190, 'Slovenia', 'SI', 10),
                    (191, 'Solomon Islands', 'SB', 10),
                    (192, 'Somalia', 'SO', 10),
                    (193, 'South Africa', 'ZA', 10),
                    (194, 'South Georgia &amp; South Sandwich Islands', 'GS', 10),
                    (195, 'Spain', 'ES', 10),
                    (196, 'Sri Lanka', 'LK', 10),
                    (197, 'St. Helena', 'SH', 10),
                    (198, 'St. Pierre and Miquelon', 'PM', 10),
                    (199, 'Sudan', 'SD', 10),
                    (200, 'Suriname', 'SR', 10),
                    (201, 'Svalbard and Jan Mayen Islands', 'SJ', 10),
                    (202, 'Swaziland', 'SZ', 10),
                    (203, 'Sweden', 'SE', 10),
                    (204, 'Switzerland', 'CH', 10),
                    (205, 'Syrian Arab Republic', 'SY', 10),
                    (206, 'Taiwan', 'TW', 10),
                    (207, 'Tajikistan', 'TJ', 10),
                    (208, 'Tanzania, United Republic of', 'TZ', 10),
                    (209, 'Thailand', 'TH', 10),
                    (210, 'Togo', 'TG', 10),
                    (211, 'Tokelau', 'TK', 10),
                    (212, 'Tonga', 'TO', 10),
                    (213, 'Trinidad and Tobago', 'TT', 10),
                    (214, 'Tunisia', 'TN', 10),
                    (215, 'Turkey', 'TR', 10),
                    (216, 'Turkmenistan', 'TM', 10),
                    (217, 'Turks and Caicos Islands', 'TC', 10),
                    (218, 'Tuvalu', 'TV', 10),
                    (219, 'Uganda', 'UG', 10),
                    (220, 'Ukraine', 'UA', 10),
                    (221, 'United Arab Emirates', 'AE', 10),
                    (222, 'United Kingdom', 'GB', 10),
                    (223, 'United States', 'US', 10),
                    (224, 'United States Minor Outlying Islands', 'UM', 10),
                    (225, 'Uruguay', 'UY', 10),
                    (226, 'Uzbekistan', 'UZ', 10),
                    (227, 'Vanuatu', 'VU', 10),
                    (228, 'Vatican City State (Holy See)', 'VA', 10),
                    (229, 'Venezuela', 'VE', 10),
                    (230, 'Viet Nam', 'VN', 10),
                    (231, 'Virgin Islands (British)', 'VG', 10),
                    (232, 'Virgin Islands (U.S.)', 'VI', 10),
                    (233, 'Wallis and Futuna Islands', 'WF', 10),
                    (234, 'Western Sahara', 'EH', 10),
                    (235, 'Yemen', 'YE', 10),
                    (237, 'Democratic Republic of Congo', 'CD', 10),
                    (238, 'Zambia', 'ZM', 10),
                    (239, 'Zimbabwe', 'ZW', 10),
                    (242, 'Montenegro', 'ME', 10),
                    (243, 'Serbia', 'RS', 10),
                    (244, 'Aaland Islands', 'AX', 10),
                    (245, 'Bonaire, Sint Eustatius and Saba', 'BQ', 10),
                    (246, 'Curacao', 'CW', 10),
                    (247, 'Palestinian Territory, Occupied', 'PS', 10),
                    (248, 'South Sudan', 'SS', 10),
                    (249, 'St. Barthelemy', 'BL', 10),
                    (250, 'St. Martin (French part)', 'MF', 10),
                    (251, 'Canary Islands', 'IC', 10),
                    (252, 'Ascension Island (British)', 'AC', 10),
                    (253, 'Kosovo, Republic of', 'XK', 10),
                    (254, 'Isle of Man', 'IM', 10),
                    (255, 'Tristan da Cunha', 'TA', 10),
                    (256, 'Guernsey', 'GG', 10),
                    (257, 'Jersey', 'JE', 10)";

        Yii::$app->db->createCommand($sql)->execute();



        $this->addColumn('restaurant', 'country_id', $this->integer()->notNull()->defaultValue(114)->after('restaurant_uuid'));


        // creates index for column `country_id`
        $this->createIndex(
                'idx-restaurant-country_id',
                'restaurant',
                'country_id'
        );

        // add foreign key for table `restaurant`
        $this->addForeignKey(
                'fk-restaurant-country_id',
                'restaurant',
                'country_id',
                'country',
                'country_id',
                'CASCADE'
        );

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {

      $this->dropForeignKey('fk-restaurant-country_id', 'restaurant');
      $this->dropIndex('idx-restaurant-country_id', 'restaurant');

      $this->dropColumn('restaurant', 'country_id');

      $this->dropTable('{{%country}}');
    }
}
