<?php

use common\models\PaymentMethod;
use yii\db\Migration;
use common\models\RestaurantInvoice;
use yii\helpers\ArrayHelper;


/**
 * Class m230301_123925_restaurant_invoice
 */
class m230301_123925_restaurant_invoice extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $invoicePaymentMethods = PaymentMethod::find()
            ->andWhere(['IN', 'payment_method_code', ["Moyasar", "Stripe"]])
            ->all();

        $invoicePaymentMethodIds = ArrayHelper::getColumn($invoicePaymentMethods, 'payment_method_id');

        $invoices = RestaurantInvoice::find()
            ->andWhere(['!=', 'invoice_status', RestaurantInvoice::STATUS_PAID])
            ->all();

        foreach ($invoices as $invoice) {

            $haveMoyasarOrder = $invoice->getInvoiceItems()
                ->joinWith(['order'])
                ->andWhere(['IN', 'order.payment_method_id', $invoicePaymentMethodIds])
                ->exists();

            //if invoice generated by mistake

            if (!$haveMoyasarOrder) {
                $invoice->invoice_status = RestaurantInvoice::STATUS_PAID;
                $invoice->save();
            }
        }
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m230301_123925_restaurant_invoice cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m230301_123925_restaurant_invoice cannot be reverted.\n";

        return false;
    }
    */
}
