version: '3.8'

networks:
  plugn-network:
    driver: bridge

services:
   
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile-nginx-prod
    container_name: plugn-backend-prod
    #command:
    #  - /bin/sh
    #  - -c
    #  - |
    #    sleep 5 && \
    #    ./init --env=Dev-Server --overwrite=All && \
    #    ./yii migrate && \
    #    sleep 1 && \
    #    ln -s /etc/nginx/sites-available/basic.conf /etc/nginx/sites-enabled/ && \
    #    service nginx restart  && \
    #    tail -f /dev/null  # Keep container running
    ports:
      - "80:80" #app endpoint
    volumes:
      - .:/home/ubuntu/plugn
      #- ./nginx/basic.conf:/etc/nginx/sites-available/basic.conf
    depends_on:
      - redis
      #- mysql
    networks:
      - plugn-network

  redis:
    image: redis:6.2.3
    ports:
      #- "7777:7777"
      - "6379:6379"
    networks:
      - plugn-network
   # command:
   #   - redis-server --port 7777
    volumes:
    - redis-data:/data

volumes:
  redis-data:
  