FROM yiisoftware/yii2-php:7.4-apache
#COPY --from=composer /usr/bin/composer /usr/bin/composer
#RUN composer install --prefer-dist
#RUN php composer.phar install --prefer-dist
#RUN init --env=Production --overwrite=All
#RUN /app/yii migrate --interactive=0 
#RUN yii_test migrate --interactive=0
#RUN yii fixture/load "*" --interactive=0
