#!/bin/bash

echo "Starting generation of fixtures for all configured templates"

./yii fixture/generate vendor  --interactive=0 --count=1

wait

./yii fixture/load Vendor --interactive=0

wait 

./yii fixture/generate restaurant  --interactive=0 --count=1

wait

./yii fixture/load Restaurant --interactive=0

wait 

./yii fixture/generate payment_method  --interactive=0 --count=2

wait

./yii fixture/load PaymentMethod --interactive=0

wait 

./yii fixture/generate restaurant_payment_method  --interactive=0 --count=2

wait

./yii fixture/load RestaurantPaymentMethod --interactive=0

wait 

./yii fixture/generate restaurant_delivery  --interactive=0 --count=10

wait

./yii fixture/load RestaurantDelivery --interactive=0

wait 

./yii fixture/generate category --interactive=0 --count=5

wait

./yii fixture/load Category --interactive=0

wait 

./yii fixture/generate item --interactive=0 --count=30

wait

./yii fixture/load Item --interactive=0

wait 

./yii fixture/generate option --interactive=0 --count=50

wait

./yii fixture/load Option --interactive=0

wait 

./yii fixture/generate extra_option --interactive=0 --count=80

wait

./yii fixture/load ExtraOption --interactive=0

wait 

./yii fixture/generate category_item --interactive=0 --count=30

wait

./yii fixture/load CategoryItem --interactive=0

wait 

./yii fixture/generate customer --interactive=0 --count=1

wait

./yii fixture/load Customer --interactive=0

#wait

#./yii fixture/generate order --interactive=0 --count=1
#
#wait
#
#./yii fixture/load Order --interactive=0
#
#wait 
#
#./yii fixture/generate order_item --interactive=0 --count=5
#
#wait
#
#./yii fixture/load OrderItem --interactive=0
#
#wait 
#
#./yii fixture/generate order_item_extra_option --interactive=0 --count=5
#
#wait
#
#./yii fixture/load OrderItemExtraOption --interactive=0

echo "Done generating all fixtures"
