<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Ticket */

?>
<div class="ticket-generated">

    <h4><?= $model->restaurant->name ?></h4>

    <p>New ticket generated by <?= Html::encode($model->agent->agent_name) ?></p>

    <p><?= $model->ticket_detail ?></p>
</div>

