<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Ticket */

?>
<div class="ticket-generated">

    <h4><?= $model->restaurant->name ?></h4>

    <?php if ($model->agent) { ?>
        <p>New ticket generated by <?= Html::encode($model->agent->agent_name) ?></p>
    <?php } else if ($model->staff) { ?>
        <p>New ticket generated by <?= Html::encode($model->staff->staff_name) ?></p>
    <?php } ?>

    <p><?= $model->ticket_detail ?></p>
</div>

