<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Ticket */

?>
<?= $model->restaurant->name ?>

<?php if ($model->agent) { ?>
    New ticket generated by <?= Html::encode($model->agent->agent_name) ?>
<?php } else if ($model->staff) { ?>
    New ticket generated by <?= Html::encode($model->staff->staff_name) ?>
<?php } ?>

<?= $model->ticket_detail ?>
