<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Ticket */

?>
<?= $model->restaurant->name ?>

New ticket generated by <?= Html::encode($model->agent->agent_name) ?>

<?= $model->ticket_detail ?>