<?php
return [
    'Development [Krushn-PC]' => [
        'path' => 'dev-krushn-pc',
        'setWritable' => [
            'backend/runtime',
            'backend/web/assets',
            'backend/web/uploads/project-files',
            'console/runtime',
            'partners/runtime',
            'partners/web/assets',
            'frontend/runtime',
            'frontend/web/assets',
            'frontend/web/uploads/',
            'api/runtime',
            'api/web/assets',
            'agent/runtime',
            'agent/web/assets',
            'shortner/runtime'
        ],
        'setExecutable' => [
            'yii',
            'yii_test',
            'fixture-generate-and-load',
            'run-tests.sh'
        ],
        'setCookieValidationKey' => [
            'backend/config/main-local.php',
            'common/config/codeception-local.php',
            'partners/config/main-local.php',
            'frontend/config/main-local.php',
            'api/config/main-local.php',
            'agent/config/main-local.php',
            'shortner/config/main-local.php',
        ],
    ],
    'Development [Krushn]' => [
        'path' => 'dev-krushn',
        'setWritable' => [
            'backend/runtime',
            'backend/web/assets',
            'backend/web/uploads/project-files',
            'console/runtime',
            'partners/runtime',
            'partners/web/assets',
            'frontend/runtime',
            'frontend/web/assets',
            'frontend/web/uploads/',
            'api/runtime',
            'api/web/assets',
            'agent/runtime',
            'agent/web/assets',
            'shortner/runtime'
        ],
        'setExecutable' => [
            'yii',
            'yii_test',
            'fixture-generate-and-load',
            'run-tests.sh'
        ],
        'setCookieValidationKey' => [
            'backend/config/main-local.php',
            'common/config/codeception-local.php',
            'frontend/config/main-local.php',
            'api/config/main-local.php',
            'agent/config/main-local.php',
            'shortner/config/main-local.php',
        ],
    ],
    'Development [Saoud]' => [
        'path' => 'dev-saoud',
        'setWritable' => [
            'partners/runtime',
            'partners/web/assets',
            'backend/runtime',
            'backend/web/assets',
            'backend/web/uploads/project-files',
            'console/runtime',
            'frontend/runtime',
            'frontend/web/assets',
            'frontend/web/uploads/',
            'api/runtime',
            'api/web/assets',
            'agent/runtime',
            'agent/web/assets',
            'shortner/runtime'
        ],
        'setExecutable' => [
            'yii',
            'yii_test',
            'fixture-generate-and-load',
            'run-tests.sh'
        ],
        'setCookieValidationKey' => [
            'backend/config/main-local.php',
            'common/config/codeception-local.php',
            'partners/config/main-local.php',
            'frontend/config/main-local.php',
            'api/config/main-local.php',
            'agent/config/main-local.php',
            'shortner/config/main-local.php',
        ],
    ],
    'Development' => [
        'path' => 'dev',
        'setWritable' => [
            'backend/runtime',
            'backend/web/assets',
            'backend/web/uploads/project-files',
            'console/runtime',
            'frontend/runtime',
            'frontend/web/assets',
            'frontend/web/uploads/',
            'api/runtime',
            'api/web/assets',
            'agent/runtime',
            'agent/web/assets',
            'shortner/runtime'
        ],
        'setExecutable' => [
            'yii',
            'yii_test',
            'fixture-generate-and-load',
            'run-tests.sh'
        ],
        'setCookieValidationKey' => [
            'backend/config/main-local.php',
            'common/config/codeception-local.php',
            'partners/config/main-local.php',
            'frontend/config/main-local.php',
            'api/config/main-local.php',
            'agent/config/main-local.php',
            'shortner/config/main-local.php',
        ],
    ],
    'Dev-Server' => [
        'path' => 'dev-server',
        'setWritable' => [
            'backend/runtime',
            'backend/web/assets',
            'backend/web/uploads/project-files',
            'console/runtime',
            'partners/runtime',
            'partners/web/assets',
            'frontend/runtime',
            'frontend/web/assets',
            'frontend/web/uploads/',
            'api/runtime',
            'api/web/assets',
            'agent/runtime',
            'agent/web/assets',
            'shortner/runtime'
        ],
        'setExecutable' => [
            'yii',
            'yii_test',
            'fixture-generate-and-load'
        ],
        'setCookieValidationKey' => [
            'backend/config/main-local.php',
            'common/config/codeception-local.php',
            'partners/config/main-local.php',
            'frontend/config/main-local.php',
            'api/config/main-local.php',
            'agent/config/main-local.php',
            'shortner/config/main-local.php',
        ],
    ],
    'Staging-Server' => [
        'path' => 'staging',
        'setWritable' => [
            'backend/runtime',
            'backend/web/assets',
            'backend/web/uploads/project-files',
            'console/runtime',
            'partners/runtime',
            'partners/web/assets',
            'frontend/runtime',
            'frontend/web/assets',
            'frontend/web/uploads/',
            'api/runtime',
            'api/web/assets',
            'agent/runtime',
            'agent/web/assets',
            'shortner/runtime'
        ],
        'setExecutable' => [
            'yii',
            'yii_test',
            'fixture-generate-and-load'
        ],
        'setCookieValidationKey' => [
            'backend/config/main-local.php',
            'common/config/codeception-local.php',
            'partners/config/main-local.php',
            'frontend/config/main-local.php',
            'api/config/main-local.php',
            'agent/config/main-local.php',
            'shortner/config/main-local.php',
        ],
    ],
    'Production' => [
        'path' => 'prod',
        'setWritable' => [
            'backend/runtime',
            'backend/web/assets',
            'backend/web/uploads/project-files',
            'console/runtime',
            'partners/runtime',
            'partners/web/assets',
            'frontend/runtime',
            'frontend/web/assets',
            'frontend/web/uploads/',
            'api/runtime',
            'api/web/assets',
            'agent/runtime',
            'agent/web/assets',
            'shortner/runtime'
        ],
        'setExecutable' => [
            'yii',
        ],
        'setCookieValidationKey' => [
            'backend/config/main-local.php',
            'partners/config/main-local.php',
            'frontend/config/main-local.php',
            'api/config/main-local.php',
            'agent/config/main-local.php',
            'shortner/config/main-local.php',
        ],
    ],
];
