apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: api
        resources:
          #requests:
          #  memory: "64Mi"
          #  cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"


