apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend
        resources:
          #requests:
          #  memory: "64Mi"
          #  cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"