<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Delivery Zone' => 'منطقة التسليم',
    'Amount Charged' => "المبلغ المشحون",
    'Created at' => "تم الإنشاء في",
    'Current Status' => "الحالة الحالية",
    'Customer ID' => "معرف العميل",
    'Gateway Fee' => "رسوم البوابة",
    'Gateway Order ID' => "معرف طلب البوابة",
    'Gateway Transaction ID' => "معرف معاملة البوابة",
    'Last activity' => "آخر نشاط",
    'Net Amount' => "المبلغ الصافي",
    'Order ID' => "معرف الطلب",
    'Payment Mode' => "وضع الدفع",
    'Payment Uuid' => "Uuid للدفع",
    'Received Callback' => "رد الاتصال المستلم",
    'Udf1' => '',
    'Udf2' => '',
    'Udf3' => '',
    'Udf4' => '',
    'Udf5' => '',
];
